language: python

python:
  - '3.8'

# command to install dependencies
install:
  - pip3 install -r requirements.txt

# command to run tests with coverage
script:
  - coverage run manage.py source='.' test

after_success:
  - coveralls
